// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace cabme.web {
	
	
	public partial class SiteMaster {
		
		protected System.Web.UI.WebControls.ContentPlaceHolder HeadContent;
		
		protected System.Web.UI.WebControls.Menu NavigationMenu;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
	}
}
